const { Router } = require("express");
const router = Router();

//* importacion de rutas
const rAdultwork = require("./routesPaginas/rAdultWork.js");
const rAmateur = require("./routesPaginas/rAmateur.js");
const rBonga = require("./routesPaginas/rBonga.js");
const rCam4 = require("./routesPaginas/rCam4.js");
const rChaturbate = require("./routesPaginas/rChaturbate.js");
const rDirty = require("./routesPaginas/rDirty.js");
const rIslive = require("./routesPaginas/rIsLive.js");
const rSender = require("./routesPaginas/rSender.js");
const rSkype = require("./routesPaginas/rSkype.js");
const rStripchat = require("./routesPaginas/rStripchat.js");
const rVx = require("./routesPaginas/rVx.js");
const rXlove = require("./routesPaginas/rXlove.js");
const rXloveNueva = require("./routesPaginas/rXloveNueva.js");
const rUser = require("./routesRegistros/rUser.js");
const rPaginas = require("./routesRegistros/rPaginas.js");
const rProducto = require("./routesRegistros/rProducto.js");
const rCompras = require("./routesRegistros/rCompras.js");
const rVenta = require("./routesRegistros/rVentas.js");
const rQuincena = require("./routesRegistros/rQuincena.js");
const rComment = require("./routesRegistros/rComments.js");
const rUserName = require("./routesRegistros/rUserName.js");
const rMoneda = require("./routesRegistros/rMoneda.js");
const rPorcentaje = require("./routesRegistros/rPorcentaje.js");
const rUbicacion = require("./routesRegistros/rUbicacion.js");
const rRelationUbicationAndPorcentaje = require("./routesRegistros/rRelationUbicationAndPorcentaje.js");
const rMondo = require("./routesPaginas/rMondo.js");
const rMyFreeCams = require("./routesPaginas/rMyFreeCams.js");
const rSakura = require("./routesPaginas/rSakura.js");
const rstreamate = require("./routesPaginas/rStreamate.js");
const rStreamRay = require("./routesPaginas/rStreamRay.js");
const rTripleSiete = require("./routesPaginas/rTripleSiete.js");
const rSearchProducto = require("./routesRegistros/rSearchProducto.js");
const rSearchUserByFortnight = require("./routesRegistros/rSearchUserByFortnight.js");
const rPrestamos = require("./routesRegistros/rPrestamos.js");
const rRojo = require("./routesRegistros/rRojo.js");

//* ejecucion de rutasrouter.use("/", rPassport);
router.use("/comentario", rComment);
router.use("/compras", rCompras);
router.use("/moneda", rMoneda);
router.use("/porcentaje", rPorcentaje);
router.use("/paginas", rPaginas);
router.use("/prestamos", rPrestamos);
router.use("/producto", rProducto);
router.use("/productos", rSearchProducto);
router.use("/quincena", rQuincena);
router.use("/quincenauser", rSearchUserByFortnight);
router.use("/ubicacion", rUbicacion);
router.use("/registro", rUser);
router.use("/venta", rVenta);
router.use("/relation", rRelationUbicationAndPorcentaje);
router.use("/username", rUserName);
router.use("/rojo", rRojo);

router.use("/corte", rAdultwork);
router.use("/amateur", rAmateur);
router.use("/bonga", rBonga);
router.use("/cam4", rCam4);
router.use("/chaturbate", rChaturbate);
router.use("/dirty", rDirty);
router.use("/islive", rIslive);
router.use("/sender", rSender);
router.use("/skype", rSkype);
router.use("/stripchat", rStripchat);
router.use("/vx", rVx);
router.use("/xlove", rXlove);
router.use("/xlovenueva", rXloveNueva);
router.use("/mondo", rMondo);
router.use("/myfreecams", rMyFreeCams);
router.use("/sakura", rSakura);
router.use("/streamate", rstreamate);
router.use("/streamray", rStreamRay);
router.use("/triplesiete", rTripleSiete);

module.exports = router;
